# Dynamo TensorRT-LLM Disaggregated Deployment - v56a Single EFA Device
# =====================================================================
# WORKAROUND TEST: Force single EFA device via FI_EFA_DEV_LIST
#
# Hypothesis: The dest_data_ep_5 deserialization failure is caused by
# NIXL attempting to serialize 32 EFA devices but failing at device 5.
# By forcing libfabric to use only device 0, we eliminate multi-rail complexity.
#
# Key change from v55:
# - Added FI_EFA_DEV_LIST=0 to force only first EFA device
#
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: trtllm-v56a-single-efa
  namespace: default
spec:
  services:
    Frontend:
      dynamoNamespace: trtllm-v56a-single-efa
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: public.ecr.aws/v9l4g5s4/dynamo-trtllm:v55-nixl-080-libfabric
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          args:
          - python3 -m dynamo.frontend --http-port 8000 --http-host 0.0.0.0
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
              nvidia.com/gpu: "0"
              vpc.amazonaws.com/efa: "0"
            requests:
              cpu: "2"
              memory: 4Gi
              nvidia.com/gpu: "0"
              vpc.amazonaws.com/efa: "0"
      envs:
        - name: DYN_ROUTER_MODE
          value: "kv"
        - name: BACKEND_MODULE
          value: "dynamo.trtllm"

    TrtllmPrefillWorker:
      dynamoNamespace: trtllm-v56a-single-efa
      componentType: worker
      subComponentType: prefill
      replicas: 1
      extraPodSpec:
        nodeSelector:
          node.kubernetes.io/instance-type: ml.p5.48xlarge
        mainContainer:
          image: public.ecr.aws/v9l4g5s4/dynamo-trtllm:v55-nixl-080-libfabric
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
              - NET_ADMIN
              - SYS_ADMIN
            privileged: true
          command:
          - /bin/bash
          - -c
          args:
            - |
              echo "=== TRT-LLM Prefill Worker v56a - SINGLE EFA DEVICE ==="
              echo "WORKAROUND: FI_EFA_DEV_LIST=0 to force single EFA device"

              # Show FI_EFA_DEV_LIST setting
              echo "FI_EFA_DEV_LIST=$FI_EFA_DEV_LIST"

              apt-get update -qq && apt-get install -y -qq libzmq5 && ldconfig

              # Verify EFA devices
              echo "=== EFA Devices ==="
              ibv_devices || echo "No IB devices"

              # Display LIBFABRIC environment
              echo "=== LIBFABRIC Environment Variables ==="
              env | grep -E '(FI_|NIXL)' | sort

              source /opt/dynamo/venv/bin/activate
              exec python -m dynamo.trtllm \
                --model-path Qwen/Qwen3-0.6B \
                --disaggregation-mode prefill \
                --extra-engine-args /config/trtllm-prefill-config.yaml
          resources:
            limits:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "1"
              vpc.amazonaws.com/efa: "1"
              hugepages-2Mi: 5120Mi
            requests:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "1"
              vpc.amazonaws.com/efa: "1"
              hugepages-2Mi: 5120Mi
          volumeMounts:
          - name: trtllm-config
            mountPath: /config
            readOnly: true
          - name: dev-infiniband
            mountPath: /dev/infiniband
          - name: hugepages
            mountPath: /dev/hugepages
        volumes:
        - name: trtllm-config
          configMap:
            name: trtllm-config-cuda13-nixl
        - name: dev-infiniband
          hostPath:
            path: /dev/infiniband
            type: DirectoryOrCreate
        - name: hugepages
          emptyDir:
            medium: HugePages
      envs:
        - name: LC_ALL
          value: "C.UTF-8"
        - name: LANG
          value: "C.UTF-8"
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: "python"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIXL_SIDE_CHANNEL_PORT
          value: "5600"
        - name: NIXL_BACKEND
          value: "LIBFABRIC"
        - name: TRTLLM_NIXL_KVCACHE_BACKEND
          value: "LIBFABRIC"
        - name: NIXL_LIBFABRIC_NUM_RAILS
          value: "1"
        - name: NIXL_SKIP_TOPOLOGY_CHECK
          value: "1"
        - name: NIXL_CONTAINER_AWARE_TOPOLOGY
          value: "1"
        - name: LD_LIBRARY_PATH
          value: "/opt/nvidia/nvda_nixl/lib/x86_64-linux-gnu:/opt/dynamo/venv/lib/python3.12/site-packages/tensorrt_llm/libs/nixl:/opt/amazon/openmpi/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/opt/amazon/efa/lib:/usr/local/ucx/lib:/usr/lib/x86_64-linux-gnu"
        # KEY WORKAROUND: Force single EFA device
        - name: FI_EFA_DEV_LIST
          value: "0"
        - name: FI_PROVIDER
          value: "efa"
        - name: FI_EFA_USE_DEVICE_RDMA
          value: "0"
        - name: FI_HMEM_P2P_DISABLED
          value: "0"
        - name: FI_EFA_ENABLE_SHM
          value: "0"
        - name: FI_MR_CACHE_MAX_COUNT
          value: "0"
        - name: FI_MR_CACHE_MONITOR
          value: "disabled"
        - name: FI_EFA_TX_SIZE
          value: "8192"
        - name: FI_EFA_RX_SIZE
          value: "8192"
        - name: FI_EFA_CQ_SIZE
          value: "16384"
        - name: FI_EFA_RECVWIN_SIZE
          value: "8192"
        - name: FI_LOG_LEVEL
          value: "info"
        - name: FI_LOG_PROV
          value: "efa"

    TrtllmDecodeWorker:
      dynamoNamespace: trtllm-v56a-single-efa
      componentType: worker
      subComponentType: decode
      replicas: 1
      extraPodSpec:
        nodeSelector:
          node.kubernetes.io/instance-type: ml.p5.48xlarge
        mainContainer:
          image: public.ecr.aws/v9l4g5s4/dynamo-trtllm:v55-nixl-080-libfabric
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
              - NET_ADMIN
              - SYS_ADMIN
            privileged: true
          command:
          - /bin/bash
          - -c
          args:
            - |
              echo "=== TRT-LLM Decode Worker v56a - SINGLE EFA DEVICE ==="
              echo "WORKAROUND: FI_EFA_DEV_LIST=0 to force single EFA device"

              echo "FI_EFA_DEV_LIST=$FI_EFA_DEV_LIST"

              apt-get update -qq && apt-get install -y -qq libzmq5 && ldconfig

              echo "=== EFA Devices ==="
              ibv_devices || echo "No IB devices"

              echo "=== LIBFABRIC Environment Variables ==="
              env | grep -E '(FI_|NIXL)' | sort

              source /opt/dynamo/venv/bin/activate
              exec python -m dynamo.trtllm \
                --model-path Qwen/Qwen3-0.6B \
                --disaggregation-mode decode \
                --extra-engine-args /config/trtllm-decode-config.yaml
          resources:
            limits:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "1"
              vpc.amazonaws.com/efa: "1"
              hugepages-2Mi: 5120Mi
            requests:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "1"
              vpc.amazonaws.com/efa: "1"
              hugepages-2Mi: 5120Mi
          volumeMounts:
          - name: trtllm-config
            mountPath: /config
            readOnly: true
          - name: dev-infiniband
            mountPath: /dev/infiniband
          - name: hugepages
            mountPath: /dev/hugepages
        volumes:
        - name: trtllm-config
          configMap:
            name: trtllm-config-cuda13-nixl
        - name: dev-infiniband
          hostPath:
            path: /dev/infiniband
            type: DirectoryOrCreate
        - name: hugepages
          emptyDir:
            medium: HugePages
      envs:
        - name: LC_ALL
          value: "C.UTF-8"
        - name: LANG
          value: "C.UTF-8"
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: "python"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIXL_SIDE_CHANNEL_PORT
          value: "5600"
        - name: NIXL_BACKEND
          value: "LIBFABRIC"
        - name: TRTLLM_NIXL_KVCACHE_BACKEND
          value: "LIBFABRIC"
        - name: NIXL_LIBFABRIC_NUM_RAILS
          value: "1"
        - name: NIXL_SKIP_TOPOLOGY_CHECK
          value: "1"
        - name: NIXL_CONTAINER_AWARE_TOPOLOGY
          value: "1"
        - name: LD_LIBRARY_PATH
          value: "/opt/nvidia/nvda_nixl/lib/x86_64-linux-gnu:/opt/dynamo/venv/lib/python3.12/site-packages/tensorrt_llm/libs/nixl:/opt/amazon/openmpi/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/opt/amazon/efa/lib:/usr/local/ucx/lib:/usr/lib/x86_64-linux-gnu"
        # KEY WORKAROUND: Force single EFA device
        - name: FI_EFA_DEV_LIST
          value: "0"
        - name: FI_PROVIDER
          value: "efa"
        - name: FI_EFA_USE_DEVICE_RDMA
          value: "0"
        - name: FI_HMEM_P2P_DISABLED
          value: "0"
        - name: FI_EFA_ENABLE_SHM
          value: "0"
        - name: FI_MR_CACHE_MAX_COUNT
          value: "0"
        - name: FI_MR_CACHE_MONITOR
          value: "disabled"
        - name: FI_EFA_TX_SIZE
          value: "8192"
        - name: FI_EFA_RX_SIZE
          value: "8192"
        - name: FI_EFA_CQ_SIZE
          value: "16384"
        - name: FI_EFA_RECVWIN_SIZE
          value: "8192"
        - name: FI_LOG_LEVEL
          value: "info"
        - name: FI_LOG_PROV
          value: "efa"
